id: I86C2CD87
source: P000246
source_file: null
initial_creation_type: input
imported: '2022-07-03T09:53:23.557547'
last_modified: '2022-07-03T09:53:23.557566'
parser: null
source_metadata:
  title: ༄༅། །བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་ཟིན་བྲིས་མཚུངས་མེད་བླ་མའི་ཞལ་རྒྱུན་བཞུགས་སོ།
  language: bo
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
